---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages
  ansible.builtin.apt:
    name:
      - openjdk-21-jre
      - git
      - unzip
      - curl
      - wget
    state: present

- name: Create Jenkins working directory
  ansible.builtin.file:
    path: /home/ubuntu/jenkins
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"

- name: Show Java version
  ansible.builtin.command: java -version
  register: java_version
  changed_when: false

- name: Display installed versions
  ansible.builtin.debug:
    msg:
      - "{{ java_version.stderr | default(java_version.stdout) }}"
