apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: space2study

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:

      - name: frontend

        image: mydockerlidia/space2study-frontend:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 3000

        env:
        - name: VITE_API_BASE_PATH
          value: "http://backend:3000"

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"
