---
- name: Create backend directory
  ansible.builtin.file:
    path: /home/lidia/apps
    state: directory

- name: Clone backend repository
  ansible.builtin.git:
    repo: git@github.com:DevOps-ProjectLevel/space2study-backend-lidia3.git
    dest: /home/lidia/apps/backend
    version: main
    update: yes

- name: Generate backend env
  ansible.builtin.template:
    src: backend.env.j2
    dest: /home/lidia/apps/backend/.env
    mode: "0600"

- name: Install backend dependencies
  ansible.builtin.command:
    cmd: npm install
    chdir: /home/lidia/apps/backend
