---
- name: Create backend directory
  ansible.builtin.file:
    path: /home/ubuntu/apps
    state: directory

- name: Clone backend repository
  ansible.builtin.git:
#    repo: https://github.com/DevOps-ProjectLevel/space2study-backend-lidia3.git
    repo: "https://{{ github_username }}:{{ github_token }}@github.com/DevOps-ProjectLevel/space2study-backend-lidia3.git"
    dest: /home/ubuntu/apps/backend
    version: main
    update: yes

- name: Generate backend env
  ansible.builtin.template:
    src: backend.env.j2
    dest: /home/ubuntu/apps/backend/.env
    owner: ubuntu
    group: ubuntu
    mode: "0600"
- name: Check node version
  command: node -v
  register: node_version

- debug:
    var: node_version.stdout

- name: Check npm version
  command: npm -v
  register: npm_version

- debug:
    var: npm_version.stdout

- name: Check make
  command: which make
  register: make_check
  ignore_errors: true

- debug:
    var: make_check

- name: Install backend dependenciec
  ansible.builtin.command:
    cmd: npm install
    chdir: /home/ubuntu/apps/backend

- name: Deploy backend systemd service
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/space2study-backend.service
    mode: "0644"
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Enable and start backend service
  ansible.builtin.systemd:
    name: space2study-backend
    enabled: true
    state: started
  become: true
