---
- hosts: control_plane
  become: true

  tasks:

    - name: Install ingress-nginx
      command: >
        kubectl apply -f
        https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.0/deploy/static/provider/cloud/deploy.yaml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: Wait for ingress controller
      command: >
        kubectl wait
        --namespace ingress-nginx
        --for=condition=available
        deployment/ingress-nginx-controller
        --timeout=300s
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: Wait for ingress controller pod
      command: >
        kubectl wait
        --namespace ingress-nginx
        --for=condition=Ready
        pod
        -l app.kubernetes.io/component=controller
        --timeout=300s
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: Wait for admission webhook
      pause:
        seconds: 20


    - name: Copy ingress manifest
      copy:
        src: ../../../k8s/ingress.yaml
        dest: /opt/k8s/ingress.yaml

    - name: Apply ingress
      command: kubectl apply -f /opt/k8s/ingress.yaml
      register: ingress_apply
      retries: 10
      delay: 10
      until: ingress_apply.rc == 0
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: Get ingress HTTP NodePort
      shell: >
        kubectl get svc ingress-nginx-controller
        -n ingress-nginx
        -o jsonpath='{.spec.ports[?(@.port==80)].nodePort}'
      register: ingress_nodeport
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: Update backend CLIENT_URL
      shell: >
        kubectl set env deployment/backend
        -n space2study
        CLIENT_URL=http://{{ hostvars[groups['worker'][0]].ansible_host | default(groups['worker'][0]) }}:{{ ingress_nodeport.stdout }}
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: Wait for backend rollout
      command: >
        kubectl rollout status deployment/backend
        -n space2study
        --timeout=300s
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
