# ansible/native/site.yml

---
- hosts: database
  become: true
  roles:
    - mongodb

- hosts: backend
  become: true
  roles:
    - backend

- hosts: frontend
  become: true
  roles:
    - frontend
