# ansible/native/site.yml

---
- hosts: database
  become: true
  roles:
    - common
    - mongodb

- hosts: backend
  become: true
  roles:
    - common
    - backend

- hosts: frontend
  become: true
  roles:
    - common
    - frontend

- hosts: agent
  become: true

  roles:
    - jenkins_agent
