grafana:
  persistence:
    enabled: false

  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

alertmanager:
  enabled: false

prometheusOperator:
  admissionWebhooks:
    enabled: false

  tls:
    enabled: false

  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

kubeStateMetrics:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

nodeExporter:
  resources:
    requests:
      cpu: 5m
      memory: 16Mi
    limits:
      cpu: 20m
      memory: 32Mi

prometheus:
  prometheusSpec:
    retention: 12h

    storageSpec: {}

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
