client_url: "http://{{ frontend_public_ip }}:3001"
server_url: "http://{{ backend_public_ip }}:3000"

api_base_path: "http://{{ backend_public_ip }}:3000"

mongodb_url: "mongodb://{{ mongodb_host }}:27017/space2study"


vault_mail_pass: "1111"
