---
- name: Create frontend directory
  ansible.builtin.file:
    path: /home/ubuntu/apps
    state: directory

- name: Clone frontend repository
  ansible.builtin.git:
#    repo: https://github.com/DevOps-ProjectLevel/space2study-frontend-lidia3.git
    repo: "https://{{ github_username }}:{{ github_token }}@github.com/DevOps-ProjectLevel/space2study-frontend-lidia3.git"
    dest: /home/ubuntu/apps/frontend
    version: main
    update: yes
  become: true
  become_user: ubuntu

- name: Generate frontend env
  ansible.builtin.template:
    src: frontend.env.j2
    dest: /home/ubuntu/apps/frontend/.env
    owner: ubuntu
    group: ubuntu
    mode: "0600"

- name: Install frontend dependencies
  ansible.builtin.command:
    cmd: npm install
    chdir: /home/ubuntu/apps/frontend
  become: true
  become_user: ubuntu

- name: Build frontend
  ansible.builtin.command:
    cmd: npm run build
    chdir: /home/ubuntu/apps/frontend
  become: true
  become_user: ubuntu

- name: Deploy frontend systemd service
  ansible.builtin.template:
    src: frontend.service.j2
    dest: /etc/systemd/system/space2study-frontend.service
    mode: "0644"
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Enable and start frontend service
  ansible.builtin.systemd:
    name: space2study-frontend
    enabled: true
    state: started
  become: true
