---


- name: Install containerd 1.7
  apt:
    name: containerd=1.7.12-0ubuntu4
    state: present

- name: Hold containerd version
  dpkg_selections:
    name: containerd
    selection: hold


#- name: Install containerd
#  apt:
#    name: containerd
#    state: present

- name: Create containerd directory
  file:
    path: /etc/containerd
    state: directory

- name: Generate default containerd config
  shell: |
    containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Enable SystemdCgroup
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Restart containerd
  service:
    name: containerd
    state: restarted
    enabled: yes
