---
- name: Install curl
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: true

- name: Check if Helm is installed
  ansible.builtin.command: helm version
  register: helm_check
  ignore_errors: true
  changed_when: false

- name: Download Helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: "0755"
  when: helm_check.rc != 0

- name: Install Helm
  ansible.builtin.command: /tmp/get_helm.sh
  when: helm_check.rc != 0

- name: Add Prometheus Helm repository
  become: true
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  ansible.builtin.command: >
    helm repo add
    {{ helm_repo_name }}
    {{ helm_repo_url }}
    --force-update

- name: Update Helm repositories
  become: true
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  ansible.builtin.command: helm repo update

- name: Copy monitoring values
  ansible.builtin.copy:
    src: values.yaml
    dest: /opt/k8s/monitoring-values.yaml
    mode: "0644"

- name: Install kube-prometheus-stack
  become: true
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  ansible.builtin.command: >
    helm upgrade --install {{ helm_release_name }}
    {{ helm_chart_name }}
    --namespace {{ monitoring_namespace }}
    --create-namespace
    --wait
    --timeout 10m
    -f /opt/k8s/monitoring-values.yaml
