---

- name: Deploy Space2Study
  hosts: app
  gather_facts: false

  tasks:

    - name: Create projects directory
      ansible.builtin.file:
        path: /home/lidia/projects
        state: directory

    - name: Clone backend repository
      ansible.builtin.git:
        repo: git@github.com:DevOps-ProjectLevel/space2study-backend-lidia3.git
        dest: /home/lidia/projects/space2study-backend-lidia3
        version: main
        update: yes
   
    - name: Generate backend env
      template:
        src: templates/backend.env.j2
        dest: /home/lidia/projects/space2study-backend-lidia3/.env.docker
        mode: "0600"

    - name: Clone frontend repository
      ansible.builtin.git:
        repo: git@github.com:DevOps-ProjectLevel/space2study-frontend-lidia3.git
        dest: /home/lidia/projects/space2study-frontend-lidia3
        version: main
        update: yes

    - name: Generate frontend env
      template:
        src: templates/frontend.env.j2
        dest: /home/lidia/projects/space2study-frontend-lidia3/.env
        mode: "0644"


    - name: Copy docker-compose
      copy:
        src: ../docker/docker-compose.yml
        dest: /home/lidia/projects/space2study-infra/docker/docker-compose.yml


    - name: Run docker compose
      command:
        cmd: docker compose up -d --build
        chdir: /home/lidia/projects/space2study-infra/docker

