---
- name: Deploy front source code
  hosts: frontend
  gather_facts: false

  tasks:
    - name: Clone frontend repository
      ansible.builtin.git:
        repo: "git@github.com:DevOps-ProjectLevel/space2study-frontend-lidia3.git"
        dest: "/home/lidia/projects/space2study-frontend-lidia3"
        version: main
        update: true
